# Generated by Django 5.0.1 on 2024-02-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='työpaikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('kuvaus', models.TextField()),
                ('sijainti', models.CharField(max_length=100)),
                ('yritys', models.CharField(max_length=100)),
                ('palkka', models.CharField(blank=True, max_length=50)),
                ('julkistuspäivämäärä', models.DateField()),
            ],
        ),
    ]
