# Generated by Django 5.0.1 on 2024-02-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harjavalta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='työpaikat',
            new_name='Jobs',
        ),
    ]
